### ISSUE TITLE
如何防止 html 也被发布在 cdn 上

### ISSUE THREAD

**Issue by honger05** [wyvernnot/qiniu-webpack-plugin#1]
如题

首先，感谢提供这么棒的工具👍

用 html-webpack-plugin 构建出来的 html 也被发布到 七牛上了。

怎么可以过滤一下呢？

**Comment by longtian** [comment]
一般都会把开发环境和产品环境的配置文件分开吧。

只要在产品环境的配置文件里就不使用 html-webpack-plugin 就行了。

**Comment by honger05** [comment]
额，对哦
