### ISSUE TITLE
include 不支持通配符？

### ISSUE THREAD

**Issue by LItterBoy-GB** [wyvernnot/qiniu-webpack-plugin#10]
include:['\*.js',"\*.png","\*.jpg","\*.css"]

**Comment by LItterBoy-GB** [comment]
抱歉 原来支持正则

**Comment by markzhou537** [comment]
@LItterBoy-GB 请问下include怎么使用啊，我需要把与src同级得static文件夹下得所有文件上传到cdn
![image](https://user-images.githubusercontent.com/15846359/43576503-1c664b58-967c-11e8-9537-f0cd1582dfd4.png)
现在时这个插件只会上传asserts里面的静态文件

**Comment by LItterBoy-GB** [comment]
看看你  asserts 与 static 的目录层级关系

**Comment by markzhou537** [comment]
![image](https://user-images.githubusercontent.com/15846359/43577491-8c6bdc2c-967e-11e8-9748-26cc5bf75af8.png)

**Comment by markzhou537** [comment]
@LItterBoy-GB 谢谢

**Comment by LItterBoy-GB** [comment]
@markflyfly 
![image](https://user-images.githubusercontent.com/28385638/43626930-a3f90e52-9726-11e8-8636-6923c8d7ab7c.png)
可以看出他是在的 assert 下查找需要上传的文件   也就是上传的时候webpack 打包的资源   主要原因也是因为只有经过webapck 打包的资源才会去替换掉它的资源 url

**Comment by markzhou537** [comment]
那也就是不经过webpack处理的静态资源无法使用此插件？

**Comment by LItterBoy-GB** [comment]
@markflyfly   不是说无法使用 而是 不经过webpack 打包的静态资源 就算上传了   浏览器在请求的时候 它走的也不是七牛云的存储空间
不过呢也是有方法处理的   自己写脚本（也可以在此插件的基础上 增加 上传文件的目录）将静态提交 
然后后台在接收到静态资源请求的时候统一进行 url重定向  将资源请求重定向（重定向还是转发你可以视情况而定）至七牛云（此种方式将导致http请求数增多）

**Comment by markzhou537** [comment]
这种方式处理不太好，那还是将外部static挪到asserts目录下引用吧

**Comment by LItterBoy-GB** [comment]
@markflyfly  可以啊  都经过webpack 打包
