### ISSUE TITLE
上传后的斜杠 为什么变成 %5C 了。。

### ISSUE THREAD

**Issue by w550** [wyvernnot/qiniu-webpack-plugin#4]
RT

**Comment by longtian** [comment]
@InTwoDisease 你的操作系统 和 qiniu-webpack-plugin 的版本号是什么呀？

**Comment by w550** [comment]
@wyvernnot
@wyvernnot 
我是 windows  10 
版本号是最新的额。
貌似原因找到了，会不会是 windows 的路径的斜杠是 \  而 linux 是 /




cp: no such file or directory: static/*
[ { hash: 'Fko5noSP3c3vfPG7pD0x7CwH-SGQ',
    key: 'fcb3f92983bdaf99b562\\static\\img\\loding@2x.cc40fac.png',
    duration: 710 },
  { hash: 'FlcBcQJxOOoXp03417D67pFjSc33',
    key: 'fcb3f92983bdaf99b562\\static\\js\\vendor.6c14cb9d841acbc27908.js',
    duration: 337 },
  { hash: 'FhwF1dqIYtkHFukAjIEXLb8TKaT8',
    key: 'fcb3f92983bdaf99b562\\static\\js\\app.22037dcac7a690fc5b25.js',
    duration: 226 },
  { hash: 'FkYnE2nJCfc4uJ1WE_rnlGSk7jF0',
    key: 'fcb3f92983bdaf99b562\\static\\css\\app.235590c8518554bb7af67e7463558179.css',
    duration: 255 },
  { hash: 'FtXCuSZEcNyhsRlptsv39fF0YRIu',
    key: 'fcb3f92983bdaf99b562\\static\\js\\vendor.6c14cb9d841acbc27908.js.map',
    duration: 631 },
  { hash: 'Fn7DpMUggxQfU6U7XEU3ljHcRI_x',
    key: 'fcb3f92983bdaf99b562\\static\\js\\app.22037dcac7a690fc5b25.js.map',
    duration: 281 },
  { hash: 'FjScTYHJSjb2dBKwjTySGBCUo3nT',
    key: 'fcb3f92983bdaf99b562\\static\\css\\app.235590c8518554bb7af67e7463558179.css.map',
    duration: 251 },
  { hash: 'FgH4Qy46e0mjgFXXdL_iCKrWl87X',
    key: 'fcb3f92983bdaf99b562\\index.html',
    duration: 252 } ]

**Comment by w550** [comment]
@wyvernnot 
这个该怎么解决呢？跪求大神

**Comment by longtian** [comment]
等我给你测测看，确实没测试过 windows :sweat_smile:

**Comment by w550** [comment]
@wyvernnot 
谢谢啦。

**Comment by w550** [comment]
赞。
